# Generated by Django 2.2.4 on 2019-09-20 21:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('admin_chat', models.CharField(blank=True, max_length=30, null=True)),
                ('new_patron_message', models.TextField(blank=True, max_length=1000, null=True)),
                ('default_channel', models.CharField(max_length=30)),
                ('new_patron_channel', models.CharField(blank=True, max_length=30, null=True)),
                ('prefixes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('role_type', models.PositiveSmallIntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild')),
            ],
        ),
    ]
