# Generated by Django 2.2.4 on 2019-09-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='admin_chat',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='default_channel',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='new_patron_channel',
        ),
    ]
