# Generated by Django 2.2.4 on 2019-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='admin_chat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='new_patron_channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='new_patron_message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
