FROM base AS geeksbot

WORKDIR /code

COPY requirements/base.txt .
COPY requirements/production.txt .
COPY requirements/geeksbot.txt .

RUN pip install -r production.txt
RUN pip install -r geeksbot.txt

CMD ["python", "-m", "geeksbot"]
