# Generated by Django 2.2.4 on 2019-09-20 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guilds', '0001_initial'),
        ('dmessages', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='message',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild'),
        ),
        migrations.AddField(
            model_name='message',
            name='tagged_channels',
            field=models.ManyToManyField(related_name='_message_tagged_channels_+', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='message',
            name='tagged_roles',
            field=models.ManyToManyField(to='guilds.Role'),
        ),
        migrations.AddField(
            model_name='message',
            name='tagged_users',
            field=models.ManyToManyField(related_name='_message_tagged_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guildinfo',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild'),
        ),
        migrations.AddField(
            model_name='guildinfo',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmessages.Message'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='completed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.Guild'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dmessages.Message'),
        ),
        migrations.AddField(
            model_name='admincomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmessages.AdminRequest'),
        ),
    ]
