# Generated by Django 2.2.4 on 2019-09-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmessages', '0002_auto_20190920_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
