# Generated by Django 2.2.4 on 2019-09-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='new_patron',
            field=models.BooleanField(default=False),
        ),
    ]
