# Generated by Django 2.2.4 on 2019-09-18 05:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190917_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discriminator',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_discriminators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, null=True, size=None),
        ),
    ]
